/* Description et exemple des classes les plus utilisées (page /dysizz-ui/classes).
   Les autres classes affichent seulement leur CSS. Ajouter ici au besoin. */
export const CLASS_DOCS = {
  // mise en page
  "dz-section": ["Section de page : grands espacements verticaux. À mettre sur le conteneur qui entoure un bloc.", null],
  "dz-container": ["Centre le contenu avec la largeur max du tenant (réglage « Largeur max »).", null],
  "dz-container-narrow": ["Comme dz-container mais étroit : idéal pour du texte long ou un formulaire.", null],
  "dz-grid": ["Grille qui s'adapte seule : les enfants se rangent en colonnes et passent à la ligne sur petit écran. À combiner avec dz-grid-2 / 3 / 4.", `<div class="dz-grid dz-grid-3"><div class="dz-card">1</div><div class="dz-card">2</div><div class="dz-card">3</div></div>`],
  "dz-grid-2": ["Grille à 2 colonnes (avec dz-grid).", null],
  "dz-grid-3": ["Grille à 3 colonnes (avec dz-grid).", null],
  "dz-grid-4": ["Grille à 4 colonnes (avec dz-grid).", null],
  "dz-split": ["Deux colonnes : texte d'un côté, visuel de l'autre. Une seule colonne sur mobile. Ajouter dz-reverse pour inverser.", `<div class="dz-split"><div class="dz-card">Texte</div><div class="dz-card">Visuel</div></div>`],
  "dz-bento": ["Grille « bento » : cases de tailles différentes (enfants avec dz-span-2, dz-span-4, dz-row-2…).", null],
  "dz-cluster": ["Aligne les enfants en ligne avec un espace régulier, passe à la ligne si besoin (boutons, badges…).", `<div class="dz-cluster"><a class="dz-btn">Un</a><a class="dz-btn dz-btn-ghost">Deux</a></div>`],
  "dz-stack": ["Empile les enfants verticalement avec un espace régulier.", `<div class="dz-stack"><div class="dz-card">A</div><div class="dz-card">B</div></div>`],
  "dz-center": ["Centre le texte et les groupes de boutons.", null],
  "dz-section-head": ["En-tête de section centré : sur-titre, titre, chapô.", `<div class="dz-section-head"><span class="dz-eyebrow">Sur-titre</span><h2 class="dz-h2">Titre de section</h2><p class="dz-lead">Une phrase d'introduction.</p></div>`],
  "dz-section-alt": ["Section avec un fond légèrement différent, pour alterner.", null],
  "dz-section-dark": ["Section sombre, même en thème clair.", null],
  "dz-section-brand": ["Section sur la couleur principale.", null],
  // texte
  "dz-display": ["Titre géant (héros).", `<div class="dz-display">Très grand titre</div>`],
  "dz-h1": ["Titre niveau 1.", `<div class="dz-h1">Titre 1</div>`],
  "dz-h2": ["Titre niveau 2 (titres de sections).", `<div class="dz-h2">Titre 2</div>`],
  "dz-h3": ["Titre niveau 3.", `<div class="dz-h3">Titre 3</div>`],
  "dz-h4": ["Titre niveau 4 (titres de cartes).", `<div class="dz-h4">Titre 4</div>`],
  "dz-lead": ["Paragraphe d'introduction, plus grand et plus doux.", `<p class="dz-lead">Un chapô qui donne envie de lire la suite.</p>`],
  "dz-eyebrow": ["Petit sur-titre en majuscules espacées, avant un titre.", `<span class="dz-eyebrow">Nouveauté</span>`],
  "dz-small": ["Petit texte discret.", `<span class="dz-small">Mis à jour il y a 2 min</span>`],
  "dz-mono": ["Police à chasse fixe (codes, chiffres alignés).", `<span class="dz-mono">ENG-142 · 48 250 €</span>`],
  "dz-gradient-text": ["Texte rempli avec le dégradé du thème.", `<span class="dz-h2 dz-gradient-text">Dégradé</span>`],
  "dz-highlight": ["Surligneur qui se dessine à l'apparition.", `<span class="dz-h3"><span class="dz-highlight dz-in">mot clé</span></span>`],
  "dz-underline": ["Soulignement décoratif.", `<span class="dz-h3 dz-underline">souligné</span>`],
  // boutons
  "dz-btn": ["Bouton principal (couleur du thème). À mettre sur un lien ou un bouton.", `<a class="dz-btn" href="#">Commencer</a>`],
  "dz-btn-ghost": ["Bouton secondaire, contour discret (avec dz-btn).", `<a class="dz-btn dz-btn-ghost" href="#">En savoir plus</a>`],
  "dz-btn-soft": ["Bouton teinté doux (avec dz-btn).", `<a class="dz-btn dz-btn-soft" href="#">Doux</a>`],
  "dz-btn-dark": ["Bouton sombre (avec dz-btn).", `<a class="dz-btn dz-btn-dark" href="#">Sombre</a>`],
  "dz-btn-light": ["Bouton clair, pour les fonds sombres (avec dz-btn).", `<a class="dz-btn dz-btn-light" href="#">Clair</a>`],
  "dz-btn-gradient": ["Bouton en dégradé (avec dz-btn).", `<a class="dz-btn dz-btn-gradient" href="#">Dégradé</a>`],
  "dz-btn-glow": ["Bouton avec halo lumineux (avec dz-btn).", `<a class="dz-btn dz-btn-glow" href="#">Halo</a>`],
  "dz-btn-shine": ["Reflet qui traverse le bouton au survol (avec dz-btn).", `<a class="dz-btn dz-btn-shine" href="#">Reflet</a>`],
  "dz-btn-link": ["Bouton qui ressemble à un lien (avec dz-btn).", `<a class="dz-btn dz-btn-link" href="#">Lien →</a>`],
  "dz-btn-sm": ["Petit bouton (avec dz-btn).", `<a class="dz-btn dz-btn-sm" href="#">Petit</a>`],
  "dz-btn-lg": ["Grand bouton (avec dz-btn).", `<a class="dz-btn dz-btn-lg" href="#">Grand</a>`],
  "dz-btn-block": ["Bouton sur toute la largeur (avec dz-btn).", null],
  "dz-icon-btn": ["Bouton carré pour une icône seule (avec dz-btn).", `<a class="dz-btn dz-btn-ghost dz-icon-btn" href="#"><i class="fas fa-bell"></i></a>`],
  // badges
  "dz-badge": ["Pastille d'étiquette (statut, nouveauté…).", `<span class="dz-badge">Nouveau</span>`],
  "dz-badge-success": ["Pastille verte (avec dz-badge).", `<span class="dz-badge dz-badge-success">Payé</span>`],
  "dz-badge-warning": ["Pastille orange (avec dz-badge).", `<span class="dz-badge dz-badge-warning">En attente</span>`],
  "dz-badge-danger": ["Pastille rouge (avec dz-badge).", `<span class="dz-badge dz-badge-danger">En retard</span>`],
  "dz-badge-neutral": ["Pastille neutre (avec dz-badge).", `<span class="dz-badge dz-badge-neutral">Brouillon</span>`],
  "dz-dot": ["Petit point de couleur (à mettre dans un badge).", `<span class="dz-badge"><span class="dz-dot"></span> En ligne</span>`],
  "dz-announce": ["Annonce cliquable en haut d'un héros.", `<a class="dz-announce" href="#"><span class="dz-badge">Nouveau</span> Version 3 disponible →</a>`],
  // cartes
  "dz-card": ["Carte : fond, bordure, arrondi, ombre douce.", `<div class="dz-card"><div class="dz-h4">Carte</div><p style="margin:0">Du contenu.</p></div>`],
  "dz-card-hover": ["La carte se soulève au survol (avec dz-card).", `<div class="dz-card dz-card-hover">Survole-moi</div>`],
  "dz-card-glass": ["Carte en verre dépoli (avec dz-card).", `<div class="dz-card dz-card-glass">Verre</div>`],
  "dz-card-soft": ["Carte teintée, sans ombre (avec dz-card).", `<div class="dz-card dz-card-soft">Douce</div>`],
  "dz-card-flat": ["Carte plate, sans ombre (avec dz-card).", `<div class="dz-card dz-card-flat">Plate</div>`],
  "dz-card-brand": ["Carte sur la couleur principale (avec dz-card).", `<div class="dz-card dz-card-brand">Couleur</div>`],
  "dz-spotlight": ["Halo qui suit la souris sur la carte.", `<div class="dz-card dz-spotlight">Passe la souris</div>`],
  "dz-border-glow": ["Bordure lumineuse qui suit la souris.", `<div class="dz-card dz-border-glow">Bordure</div>`],
  "dz-icon": ["Pastille carrée pour une icône.", `<span class="dz-icon"><i class="fas fa-bolt"></i></span>`],
  "dz-icon-lg": ["Pastille d'icône plus grande (avec dz-icon).", `<span class="dz-icon dz-icon-lg"><i class="fas fa-bolt"></i></span>`],
  "dz-icon-round": ["Pastille d'icône ronde (avec dz-icon).", `<span class="dz-icon dz-icon-round"><i class="fas fa-bolt"></i></span>`],
  "dz-icon-gradient": ["Pastille d'icône en dégradé (avec dz-icon).", `<span class="dz-icon dz-icon-gradient"><i class="fas fa-bolt"></i></span>`],
  "dz-avatar": ["Avatar rond avec initiales (ou une image dedans).", `<span class="dz-avatar">SD</span>`],
  // application
  "dz-kpi": ["Carte d'indicateur : libellé, gros chiffre, tendance.", `<div class="dz-kpi"><div class="dz-kpi-label">Chiffre d'affaires <span class="dz-trend dz-trend-up">▲ 12 %</span></div><div class="dz-kpi-value">48 250 €</div></div>`],
  "dz-trend-up": ["Tendance positive (vert).", `<span class="dz-trend dz-trend-up">▲ 12 %</span>`],
  "dz-trend-down": ["Tendance négative (rouge).", `<span class="dz-trend dz-trend-down">▼ 3 %</span>`],
  "dz-progress": ["Barre de progression (un span dedans). Ajouter dz-progress-72 pour 72 %.", `<div class="dz-progress dz-progress-72"><span style="width:72%"></span></div>`],
  "dz-kbd": ["Touche de clavier.", `<span class="dz-kbd">Ctrl K</span>`],
  "dz-callout": ["Encadré d'information (variantes dz-callout-success…).", `<div class="dz-callout"><div>Une information utile.</div></div>`],
  "dz-empty": ["État vide centré (icône, titre, bouton).", null],
  "dz-chip": ["Puce cliquable (filtres). dz-active pour la puce choisie.", `<div class="dz-chips"><span class="dz-chip dz-active">Tous</span><span class="dz-chip">Actifs</span></div>`],
  "dz-switch": ["Interrupteur visuel.", null],
  "dz-window": ["Cadre de fenêtre (barre avec 3 points) pour mettre en scène une capture.", null],
  // fonds, effets, utilitaires
  "dz-hero": ["Héros : grand premier écran.", null],
  "dz-glass": ["Effet verre dépoli.", `<div class="dz-glass" style="padding:1rem;border-radius:12px">Verre</div>`],
  "dz-bg-surface": ["Fond « surface » du thème.", `<div class="dz-bg-surface" style="padding:1rem">Surface</div>`],
  "dz-bg-soft": ["Fond doux teinté.", `<div class="dz-bg-soft" style="padding:1rem">Doux</div>`],
  "dz-bg-gradient": ["Fond en dégradé du thème.", `<div class="dz-bg-gradient" style="padding:1rem;color:#fff">Dégradé</div>`],
  "dz-shadow": ["Ombre moyenne.", `<div class="dz-card dz-shadow">Ombre</div>`],
  "dz-shadow-lg": ["Grande ombre.", `<div class="dz-card dz-shadow-lg">Grande ombre</div>`],
  "dz-rounded": ["Angles arrondis du thème.", null],
  "dz-rounded-lg": ["Grands angles arrondis.", null],
  "dz-border": ["Bordure fine du thème.", null],
  "dz-divider": ["Séparateur horizontal.", `<div class="dz-divider"></div>`],
  "dz-sticky": ["Reste collé en haut pendant le défilement.", null],
  "dz-cover": ["Image qui remplit son cadre sans se déformer.", null],
  "dz-aspect-video": ["Cadre au format 16/9.", null],
  "dz-text-primary": ["Texte couleur principale.", `<span class="dz-text-primary">Texte couleur</span>`],
  "dz-text-soft": ["Texte adouci.", `<span class="dz-text-soft">Texte doux</span>`],
  "dz-text-mute": ["Texte très discret.", `<span class="dz-text-mute">Texte discret</span>`],
  "dz-hide-mobile": ["Caché sur mobile.", null],
  // animations
  "dz-reveal": ["Apparaît en glissant quand on arrive dessus. Variantes : dz-reveal-fade, -zoom, -blur, -left, -right, -flip.", null],
  "dz-stagger": ["Sur un parent : ses enfants apparaissent l'un après l'autre.", null],
  "dz-parallax": ["Se déplace plus lentement que la page (profondeur). Variantes -slow, -fast, -reverse.", null],
  "dz-tilt": ["S'incline en 3D en suivant la souris.", `<div class="dz-card dz-tilt">Incline-moi</div>`],
  "dz-magnetic": ["Attiré par la souris (boutons).", `<a class="dz-btn dz-magnetic" href="#">Aimanté</a>`],
  "dz-float": ["Flotte doucement en boucle.", null],
  "dz-marquee": ["Bandeau qui défile en boucle (logos, mots).", null],
  // transitions et bords
  "dz-edge-wave": ["Bas de la section en vague. Aussi : dz-edge-slant, -curve, -arc, -zigzag, -steps ; et dz-edge-top-… pour le haut.", null],
  "dz-edge-fade": ["La section se fond dans la page en haut et en bas.", null],
  "dz-edge-round-top": ["La section monte sur la précédente avec de grands coins arrondis.", null],
};
export const EXTRA_DOCS = {
  "dz-counter": ["Anime le nombre écrit dans le texte à l'apparition.", `<span class="dz-h2 dz-counter">48 250 €</span>`],
  "dz-typewriter": ["Machine à écrire : écrire « mot 1 | mot 2 | mot 3 ».", `<span class="dz-h3 dz-typewriter">Design | Code | Lancement</span>`],
  "dz-countdown": ["Compte à rebours : le texte est la date (2026-12-31 18:00).", null],
  "dz-theme-toggle": ["Bascule clair / sombre au clic.", null],
  "dz-confetti": ["Lance des confettis au clic.", `<a class="dz-btn dz-confetti" href="#">🎉 Clique</a>`],
  "dz-copy": ["Copie le code (ou le texte) du bloc au clic.", null],
  "dz-dismiss": ["Ferme (masque) son parent au clic.", null],
  "dz-close": ["Ferme le panneau (tiroir, feuille) qui le contient.", null],
  "dz-zoomable": ["Image agrandie en plein écran au clic.", null],
  "dz-words": ["Texte qui s'éclaire mot à mot au défilement.", null],
  "dz-letters": ["Lettres qui montent une à une à l'apparition.", null],
  "dz-slider": ["Carrousel : les enfants défilent.", null],
  "dz-tabs-auto": ["Onglets qui changent tout seuls (avec dz-tabs).", null],
  "dz-open-ID": ["Ouvre l'élément dont l'identifiant est ID (tiroir, feuille, modale). Ex. dz-open-panier.", null],
  "dz-page-tr-NOM": ["Sur n'importe quel conteneur : transition des sections de CETTE page (fade, rise, zoom, blur, tilt, curtain, wipe, cover, stack, depth, fadeout, none).", null],
  "dz-tr-NOM": ["Sur une section : sa propre transition (mêmes noms).", null],
  "dz-morph-COULEUR": ["Sur une section : couleur de fond de la page quand on y arrive (primary, surface, bg, accent…).", null],
};
